baseURL = 'https://intro-to-web-dev-curriculum.netlify.app/'
languageCode = 'en-us'
title = 'Introduction to Web Dev'
theme = "hugo-theme-relearn"

canonifyURLs = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  themeVariant = ["lc-light", "lc-dark-blue", "lc-dark-blue-two"]
  nodeUpdateDate = "December 2023"
  nodeVersion = "20.9.0"
  nodeShortVersion = "20.x.x"
